name: Lerna Test

on:
  workflow_call:

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    concurrency:
      group: lerna-test-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read

    env:
      CI: true

    strategy:
      matrix:
        node-version:
          - 16

    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6
        with:
          lfs: true

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - run: npx lerna run test

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - run: echo "success"
