name: Lerna Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    concurrency:
      group: lerna-publish-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write

    env:
      CI: true

    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stoe'

      - name: npm install
        run: |
          npm set-script prepare ""
          npm install --ignore-scripts --pure-lockfile
          git ls-files -z . | xargs -0 git update-index --assume-unchanged

      - run: npx lerna publish from-package --yes --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
