name: Lerna Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    concurrency:
      group: lerna-publish-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write

    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stoe'

      - name: npm install
        run: |
          npm pkg delete scripts.prepare
          npm install --ignore-scripts --pure-lockfile
          git ls-files -z . | xargs -0 git update-index --assume-unchanged

      - run: npx lerna publish from-package --yes --registry https://npm.pkg.github.com
