name: reusable publish (lerna)

on:
  workflow_call:
    inputs:
      npm:
        description: 'Publish lerna monorepo to NPM'
        type: boolean
        default: false
      gh:
        description: 'Publish lerna monorepo to GitHub Packages'
        type: boolean
        default: true
    secrets:
      npm_token:
        required: false

env:
  NODE_VERSION: 22
  NPM_SCOPE: '@stoe'

jobs:
  publish_npm:
    if: ${{ inputs.npm }}

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-npm-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          scope: ${{ env.NPM_SCOPE }}
          registry-url: 'https://registry.npmjs.org'

      - name: NPM config
        run: |
          npm pkg delete scripts.prepare
          npm install --ignore-scripts --pure-lockfile
          git ls-files -z . | xargs -0 git update-index --assume-unchanged

      - name: GitHub Packages publish
        run: npx lerna publish from-package --yes --registry https://registry.npmjs.org

  publish_gh:
    if: ${{ inputs.gh }}

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-gh-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write

    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          scope: ${{ env.NPM_SCOPE }}
          registry-url: 'https://npm.pkg.github.com'

      - name: NPM config
        run: |
          npm pkg delete scripts.prepare
          npm install --ignore-scripts --pure-lockfile
          git ls-files -z . | xargs -0 git update-index --assume-unchanged

      - name: GitHub Packages publish
        run: npx lerna publish from-package --yes --registry https://npm.pkg.github.com
