name: Lerna Test

on:
  workflow_call:

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    concurrency:
      group: lerna-test-${{ github.ref }}
      cancel-in-progress: true

    permissions: read-all

    env:
      CI: true

    strategy:
      matrix:
        node-version:
          - 16

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          lfs: true

      - uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - run: npx lerna run test

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - run: echo "success"
