name: reusable test (lerna)

on:
  workflow_call:

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version:
          - 18
          - 20

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --ignore-scripts --pure-lockfile

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npx lerna run test

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - name: Success
        run: echo "success"
