name: reusable publish (workspace package)

on:
  workflow_call:
    inputs:
      npm:
        description: 'Publish workspaces to NPM'
        type: boolean
        default: false
      gh:
        description: 'Publish workspaces to GitHub Packages'
        type: boolean
        default: true
    secrets:
      npm_token:
        required: false

jobs:
  publish_npm:
    name: Publish to NPM
    if: ${{ inputs.npm }}

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-npm-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: '@stoe'

      - name: NPM config
        run: |
          npm pkg delete scripts.prepare
          npm install --ignore-scripts --pure-lockfile
          git ls-files -z . | xargs -0 git update-index --assume-unchanged

      - name: NPM publish
        run: npm publish --provenance --access public --workspaces

  publish_gh:
    name: Publish to GitHub
    if: ${{ inputs.gh }}

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-gh-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write

    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stoe'

      - name: NPM config
        run: |
          npm pkg delete scripts.prepare
          npm install --ignore-scripts --pure-lockfile
          git ls-files -z . | xargs -0 git update-index --assume-unchanged

      - name: GitHub Packages publish
        run: npm publish --access public --workspaces
